version: '3'
services:
  ip_master:
    image: photon:latest
    restart: always
    #env_file: ./.env.dev
    build: .
    ports:
      - 55555:55555
    networks:
      - db_network
      - app_network
    volumes:
      - ./alembic:/usr/src/ip_master/alembic
    depends_on: 
      - postgres
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IP-Master-Passw0rd123!
      POSTGRES_DB: IP-Master
    image: postgres:15
    networks:
      - db_network
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data-15:/var/lib/postgresql/data
networks:
  db_network:
    driver: bridge
  app_network:
    driver: bridge

volumes: 
  postgres_data: