# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipAddress.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fipAddress.proto\x12\x08\x64\x62\x41\x63\x63\x65ss\"\x86\x02\n\tipAddress\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tsubnet_id\x18\x02 \x01(\t\x12\x11\n\tipAddress\x18\x03 \x01(\t\x12\x12\n\nis_gateway\x18\x04 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08hostname\x18\x06 \x01(\t\x12\x12\n\nmacAddress\x18\x07 \x01(\t\x12\r\n\x05owner\x18\x08 \x01(\t\x12\x10\n\x08state_id\x18\t \x01(\t\x12\x14\n\x0c\x64\x61taLastSeen\x18\n \x01(\t\x12\x16\n\x0e\x64\x61teLastEdited\x18\x0b \x01(\t\x12\x13\n\x0b\x64\x61teCreated\x18\x0c \x01(\t\x12\x14\n\x0cis_available\x18\r \x01(\x08\" \n\x12IpAddressIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x14IpAddressNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x16IpAddressSubnetRequest\x12\x11\n\tsubnet_id\x18\x01 \x01(\t\";\n\x11IpAddressResponse\x12&\n\tipAddress\x18\x01 \x01(\x0b\x32\x13.dbAccess.ipAddress2\xc1\x04\n\tIpAddress\x12O\n\x10GetIpAddressById\x12\x1c.dbAccess.IpAddressIdRequest\x1a\x1b.dbAccess.IpAddressResponse\"\x00\x12S\n\x12GetIpAddressByName\x12\x1e.dbAccess.IpAddressNameRequest\x1a\x1b.dbAccess.IpAddressResponse\"\x00\x12W\n\x14GetIpAddressBySubnet\x12 .dbAccess.IpAddressSubnetRequest\x1a\x1b.dbAccess.IpAddressResponse\"\x00\x12\x42\n\x0c\x41\x64\x64IpAddress\x12\x13.dbAccess.ipAddress\x1a\x1b.dbAccess.IpAddressResponse\"\x00\x12\x45\n\x0fUpdateIpAddress\x12\x13.dbAccess.ipAddress\x1a\x1b.dbAccess.IpAddressResponse\"\x00\x12R\n\x13\x44\x65leteIpAddressById\x12\x1c.dbAccess.IpAddressIdRequest\x1a\x1b.dbAccess.IpAddressResponse\"\x00\x12V\n\x15\x44\x65leteIpAddressByName\x12\x1e.dbAccess.IpAddressNameRequest\x1a\x1b.dbAccess.IpAddressResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipAddress_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IPADDRESS._serialized_start=30
  _IPADDRESS._serialized_end=292
  _IPADDRESSIDREQUEST._serialized_start=294
  _IPADDRESSIDREQUEST._serialized_end=326
  _IPADDRESSNAMEREQUEST._serialized_start=328
  _IPADDRESSNAMEREQUEST._serialized_end=364
  _IPADDRESSSUBNETREQUEST._serialized_start=366
  _IPADDRESSSUBNETREQUEST._serialized_end=409
  _IPADDRESSRESPONSE._serialized_start=411
  _IPADDRESSRESPONSE._serialized_end=470
  _IPADDRESS._serialized_start=473
  _IPADDRESS._serialized_end=1050
# @@protoc_insertion_point(module_scope)
