"""Updated dateLastEdited column

Revision ID: 2bb8d66f06da
Revises: f669de5de194
Create Date: 2023-04-12 13:10:29.488952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb8d66f06da'
down_revision = 'f669de5de194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
