"""Updated dateLastEdited column

Revision ID: 40286ea6dd91
Revises: 6366ddce695c
Create Date: 2023-04-12 15:09:35.161500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40286ea6dd91'
down_revision = '6366ddce695c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subnets', 'name',
               existing_type=sa.VARCHAR(length=48),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subnets', 'name',
               existing_type=sa.VARCHAR(length=48),
               nullable=True)
    # ### end Alembic commands ###
