"""Updated dateLastEdited column

Revision ID: 6366ddce695c
Revises: 2bb8d66f06da
Create Date: 2023-04-12 13:15:46.640173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6366ddce695c'
down_revision = '2bb8d66f06da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
