"""Added description to subnets

Revision ID: 6380e945d6be
Revises: c96a32255193
Create Date: 2023-04-12 15:48:40.021892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6380e945d6be'
down_revision = 'c96a32255193'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
