"""Added is_available to ipAddresses table

Revision ID: 98c06c70b504
Revises: b046cf164c8c
Create Date: 2023-04-11 16:17:17.903758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c06c70b504'
down_revision = 'b046cf164c8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipAddresses', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ipAddresses', 'is_available')
    # ### end Alembic commands ###
