"""Added description to subnets

Revision ID: b83d1a0b4944
Revises: fb310a6087d9
Create Date: 2023-04-12 16:23:19.406430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83d1a0b4944'
down_revision = 'fb310a6087d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
