"""Added description to subnets

Revision ID: c96a32255193
Revises: 40286ea6dd91
Create Date: 2023-04-12 15:11:54.651261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96a32255193'
down_revision = '40286ea6dd91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subnets', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subnets', 'description')
    # ### end Alembic commands ###
