"""Updated dateLastEdited column

Revision ID: d54ac1f0ccec
Revises: 98c06c70b504
Create Date: 2023-04-12 12:58:23.531125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54ac1f0ccec'
down_revision = '98c06c70b504'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
