"""Users_Table

Revision ID: f382acc01b94
Revises: e6555c97aef5
Create Date: 2023-04-21 15:27:53.476801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f382acc01b94'
down_revision = 'e6555c97aef5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
