"""Updated dateLastEdited column

Revision ID: f669de5de194
Revises: d54ac1f0ccec
Create Date: 2023-04-12 12:59:55.493742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f669de5de194'
down_revision = 'd54ac1f0ccec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
